package com.ling.linginnerflow.pattern.entity;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * A versioned set of EvidenceItems justifying one PatternInstance (§9).
 *
 * EvidenceChains are immutable once written; engine refreshes produce a new
 * EvidenceChain linked to the same PatternInstance, preserving history.
 * The PatternInstance.evidenceChainId always points to the most recent chain.
 */
@Data
@Entity
@Table(name = "evidence_chain")
public class EvidenceChain {

    /** UUID primary key — assigned in @PrePersist. */
    @Id
    private String id;

    /** FK to the PatternInstance this chain supports. */
    @Column(nullable = false)
    private String patternInstanceId;

    /** Timestamp when this chain was generated by the engine. */
    @Column(nullable = false)
    private LocalDateTime generatedAt;

    /**
     * Model + prompt version string (e.g. "gpt-4o:pattern-engine-v1.2:prompt-sha=abc123").
     * Used for offline evaluation and reproducibility auditing.
     */
    @Column(nullable = false)
    private String generatorVersion;

    @PrePersist
    public void prePersist() {
        if (id == null) {
            id = UUID.randomUUID().toString();
        }
        if (generatedAt == null) {
            generatedAt = LocalDateTime.now();
        }
    }
}
